version: "3.8"

volumes:
  postgres-data: {}
  pgadmin-data: {}
  elasticsearch: {}

services:
  db:
    container_name: postgres_container
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: kellian
      POSTGRES_PASSWORD: kellian
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backendnetwork
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: no
    environment:
      PGADMIN_DEFAULT_EMAIL: kellian.bechtel@proton.me
      PGADMIN_DEFAULT_PASSWORD: kellian
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - backendnetwork

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.7.1
    # 8.x
    environment:
      [
        "CLI_JAVA_OPTS=-Xms2g -Xmx2g",
        "bootstrap.memory_lock=true",
        "discovery.type=single-node",
        "xpack.security.enabled=false",
        "xpack.security.enrollment.enabled=false",
      ]
    ports:
      - 9200:9200
    networks:
      - backendnetwork
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: "2.0"
        reservations:
          cpus: "1.0"

  kibana:
    image: kibana:8.7.1
    container_name: kibana
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
    ports:
      - 5601:5601
    networks:
      - backendnetwork
    deploy:
      resources:
        limits:
          cpus: "2.0"
        reservations:
          cpus: "1.0"


networks:
  backendnetwork:
