[application]

# dioxus project name
name = "ChatApp"

# default platform
# you can also use `dioxus serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "web"

[web.app]

# HTML title tag content
title = "Chat app"


# include `assets` in web platform
[web.resource]

# CSS style file
style = ["reset.css"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
